name = "LineCableToolbox"
uuid = "dffb7669-8cd4-4628-99dd-7694e356ba37"
authors = ["Amauri Martins"]
version = "1.0.0-DEV"

[deps]
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"

[compat]
Measurements = "2.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
