project:
  output-dir: _site

# CHANGE THIS ONE LINE ↓ to your GitHub "owner/repo"
metadata:
  repo_nwo: "Electa-Git/LineCableModels.jl"

format:
  revealjs:
    thebe: true
    code-tools: true
    theme: [default, assets/corporate.scss]
    slide-number: true
    controls: true
    progress: true
    transition: slide
    background-transition: fade
    # logo: assets/logo.svg   # uncomment when you add a logo

execute:
  freeze: auto
