function routes(identifier::Val{:Bridges1995})
    (
        self = formula_method(identifier, earth_impedance, Val(:self)),
        mutual = formula_method(identifier, earth_impedance, Val(:mutual)),
        Γ = formula_method(identifier, propagation_constant)
    )
end

function assumptions(::Val{:Bridges1995})
    (
        air = _lossless,
        earth = _conductive,
        permeability = vacuum_permeability
    )
end

propagation(::Val{:Bridges1995}) = Val(:zero)
"""
$(TYPEDSIGNATURES)

**Identification.** Low-frequency radial approximation for a bare conductor
buried in a conductive half-space.

**Expression.**

```math
Z_{e,ii}=-\\frac{j\\omega\\mu_0}{2\\pi}
\\ln\\left(\\frac{e_c\\gamma_1r_i}{2}\\right),\\qquad
e_c=1.7811,\\quad \\gamma_1^2=j\\omega\\mu_0\\sigma_1.
```

This is a single-cable self term. The cited derivation does not provide a
mutual-impedance specialization for a multiconductor cable system.

**Reference.** G. E. J. Bridges, “Fields Generated by Bare and Insulated
Cables Buried in a Lossy Half-Space,” *IEEE Transactions on Geoscience and
Remote Sensing*, 30(1), 140–146, 1992; G. E. J. Bridges, “Transient Plane Wave
Coupling to Bare and Insulated Cables Buried in a Lossy Half-Space,” *IEEE
Transactions on Electromagnetic Compatibility*, 37(1), 62–70, 1995. The
implemented radial approximation is the Bridges form reproduced in Ametani
et al., IET, 2021.
"""
description(::Formula{:Bridges1995}) =
    "Bridges buried single-cable approximation (1992/1995)"

function propagation_constant(::Val{:Bridges1995}, jω, permeability, permittivity)
    return (Γ = zero(jω), squared = zero(jω))
end

function (formula::Formula{:Bridges1995})(rho, epsilon, mu, jω, Γ, segments = nothing)
    return _homogeneous_functor(
        Val(:Bridges1995), formula, rho, epsilon, mu, jω, Γ, segments)
end

raw"""
Evaluate Bridges' buried single-cable impedance:

```math
Z_{e,ii}=-\frac{j\omega\mu_0}{2\pi}
\ln\left(\frac{e_c\gamma_1r_i}{2}\right),\qquad
e_c=1.7811,\quad \gamma_1^2=j\omega\mu_0\sigma_1.
```

The cable outer radius is supplied by the self-pair separation field.
"""
function earth_impedance(
        ::Val{:Bridges1995}, ::Val{:self}, functor, pair
)
    _require(pair, Val(:underground))
    state = functor.state
    e_c = oftype(pair.separation, 1.7811)
    return -state.jω * state.mu[1] / (2π) *
           log(e_c * state.gamma[2] * pair.separation / 2)
end

function earth_impedance(
        ::Val{:Bridges1995}, ::Val{:mutual}, functor, pair
)
    _require(pair, Val(:underground))
    throw(ArgumentError(
        "Bridges1995 supplies only a single-cable self impedance; " *
        "the cited formula has no mutual route"
    ))
end

:Bridges1995
