function _pscad_output_path(system::LineCableSystem, file_name)
    if file_name === nothing
        return joinpath(@__DIR__, "$(system.system_id)_export.pscx")
    end
    requested = isabspath(file_name) ? String(file_name) : abspath(file_name)
    directory, name = splitdir(requested)
    return joinpath(directory, "$(system.system_id)_$name")
end

const _PSCAD_DEFINITION_DATE = "0"
const _PSCAD_IDS = (
    station = 100000001,
    station_wire = 100000002,
    main_instance = 100000003,
    main = 100000004,
    main_rectangle = 100000005,
    main_text = 100000006,
    cable_wire = 100000007,
    cable_instance = 100000008,
    cable_system = 100000009,
    first_physical_component = 100000010
)

function _pscad_project_settings!(project)
    settings = Pair{String, String}[
        "creator" => "LineCableModels.jl",
        "time_duration" => "0.5",
        "time_step" => "5",
        "sample_step" => "250",
        "chatter_threshold" => ".001",
        "branch_threshold" => ".0005",
        "StartType" => "0",
        "startup_filename" => "\$(Namespace).snp",
        "PlotType" => "0",
        "output_filename" => "\$(Namespace).out",
        "SnapType" => "0",
        "SnapTime" => "0.3",
        "snapshot_filename" => "\$(Namespace).snp",
        "MrunType" => "0",
        "Mruns" => "1",
        "Scenario" => "",
        "Advanced" => "14335",
        "sparsity_threshold" => "200",
        "Options" => "16",
        "Build" => "18",
        "Warn" => "0",
        "Check" => "0",
        "description" => "Generated by LineCableModels.jl",
        "Debug" => "0"
    ]
    return _pscad_paramlist!(project, settings; name = "Settings")
end

function _pscad_project_scaffolding!(project)
    addelement!(project, "Layers")
    addelement!(project, "List")["classid"] = "Settings"
    addelement!(project, "bookmarks")
    substitutions = addelement!(project, "GlobalSubstitutions")
    substitutions["name"] = "Default"
    addelement!(substitutions, "List")["classid"] = "Sub"
    addelement!(substitutions, "List")["classid"] = "ValueSet"
    _pscad_paramlist!(substitutions, ["Current" => ""])
    return project
end

function _pscad_station_definition!(definitions, namespace::AbstractString)
    station = addelement!(definitions, "Definition")
    _pscad_attributes!(station,
        (
            id = _PSCAD_IDS.station,
            classid = "StationDefn",
            name = "DS",
            group = "",
            url = "",
            version = "",
            build = "",
            crc = -1,
            view = "false"
        ))
    _pscad_paramlist!(station, ["Description" => ""]; name = "")
    schematic = addelement!(station, "schematic")
    schematic["classid"] = "StationCanvas"
    _pscad_canvas_params!(schematic)
    addelement!(schematic, "grouping")
    _pscad_wire!(
        schematic,
        _PSCAD_IDS.station_wire,
        _PSCAD_IDS.main_instance,
        "Branch",
        "Main",
        "Main",
        "$namespace:Main",
        Pair{String, String}[];
        x = 180,
        y = 180,
        width = 66,
        height = 82
    )
    return station
end

function _pscad_main_instance_parameters(system::LineCableSystem, base_frequency)
    length_km = system.line_length / 1000
    return Pair{String, String}[
        "Name" => system.system_id,
        "R" => "#NaN",
        "X" => "#NaN",
        "B" => "#NaN",
        "Freq" => _pscad_value(base_frequency),
        "Length" => _pscad_value(length_km),
        "Dim" => "0",
        "Mode" => "0",
        "CoupleEnab" => "0",
        "CoupleName" => "row",
        "CoupleOffset" => "0.0 [m]",
        "CoupleRef" => "0",
        "tname" => "tandem_segment",
        "sfault" => "0",
        "linc" => "$(_pscad_value(length_km)) [km]",
        "steps" => "3",
        "gen_cnst" => "1",
        "const_path" => "%TEMP%\\my_constants_file.tlo",
        "Date" => _PSCAD_DEFINITION_DATE
    ]
end

function _pscad_main_definition!(
        definitions,
        system::LineCableSystem,
        base_frequency
)
    namespace = system.system_id
    main = addelement!(definitions, "Definition")
    _pscad_attributes!(main,
        (
            id = _PSCAD_IDS.main,
            classid = "UserCmpDefn",
            name = "Main",
            group = "",
            url = "",
            version = "",
            build = "",
            crc = -1,
            view = "false",
            date = _PSCAD_DEFINITION_DATE
        ))
    _pscad_paramlist!(main, ["Description" => ""]; name = "")
    form = addelement!(main, "form")
    _pscad_attributes!(form, (name = "", w = 320, h = 400, splitter = 60))

    graphics = addelement!(main, "graphics")
    _pscad_attributes!(graphics, (viewBox = "-200 -200 200 200", size = 2))
    rectangle = addelement!(graphics, "Gfx")
    _pscad_attributes!(rectangle,
        (
            id = _PSCAD_IDS.main_rectangle,
            classid = "Graphics.Rectangle",
            x = -36,
            y = -36,
            w = 72,
            h = 72
        ))
    _pscad_paramlist!(rectangle,
        [
            "color" => "Black",
            "dasharray" => "0",
            "thickness" => "0",
            "port" => "",
            "fill_style" => "0",
            "fill_fg" => "Black",
            "fill_bg" => "Black",
            "cond" => "true"
        ])
    text = addelement!(graphics, "Gfx")
    _pscad_attributes!(text, (
        id = _PSCAD_IDS.main_text,
        classid = "Graphics.Text",
        x = 0,
        y = 0
    ))
    _pscad_paramlist!(text,
        [
            "text" => "%:Name",
            "anchor" => "0",
            "full_font" => "Tahoma, 13world",
            "angle" => "0",
            "color" => "Black",
            "cond" => "true"
        ])

    schematic = addelement!(main, "schematic")
    schematic["classid"] = "UserCanvas"
    _pscad_canvas_params!(schematic; user = true)
    addelement!(schematic, "grouping")
    _pscad_wire!(
        schematic,
        _PSCAD_IDS.cable_wire,
        _PSCAD_IDS.cable_instance,
        "Cable",
        "$namespace:CableSystem",
        "$namespace:CableSystem",
        "$namespace:CableSystem",
        _pscad_main_instance_parameters(system, base_frequency);
        x = 72,
        y = 36,
        width = 107,
        height = 128,
        crc = -1
    )
    return main
end

function _pscad_hierarchy!(project, namespace::AbstractString)
    addelement!(project, "List")["classid"] = "Resource"
    hierarchy = addelement!(project, "hierarchy")
    station = addelement!(hierarchy, "call")
    _pscad_attributes!(station,
        (
            link = _PSCAD_IDS.station,
            name = "$namespace:DS",
            z = -1,
            view = "false",
            instance = 0
        ))
    main = addelement!(station, "call")
    _pscad_attributes!(main,
        (
            link = _PSCAD_IDS.main_instance,
            name = "$namespace:Main",
            z = -1,
            view = "false",
            instance = 0
        ))
    cable = addelement!(main, "call")
    _pscad_attributes!(cable,
        (
            link = _PSCAD_IDS.cable_instance,
            name = "$namespace:CableSystem",
            z = -1,
            view = "true",
            instance = 0
        ))
    return hierarchy
end

function _pscad_part_parameters(component, index::Int, angular_frequency)
    names = ("C", "S", "A", "O")
    radii = (("R1", "R2", "R3"), ("R4", "R4", "R5"),
        ("R6", "R6", "R7"), ("R8", "R8", "R9"))
    resistivities = ("RHOC", "RHOS", "RHOA", "RHOO")
    permeabilities = ("PERMC", "PERMS", "PERMA", "PERMO")
    dielectric_permittivities = ("EPS1", "EPS2", "EPS3", "EPS4")
    dielectric_permeabilities = ("PERM1", "PERM2", "PERM3", "PERM4")
    loss_tangents = ("LT1", "LT2", "LT3", "LT4")
    conductor_name = "CONNAM$index"
    inner_name, outer_name, insulation_name = radii[index]
    conductor = component.conductor
    dielectric = component.dielectric
    capacitance = dielectric.shunt_capacitance
    conductance = dielectric.shunt_conductance
    loss = iszero(capacitance) ? zero(capacitance) :
           conductance / (angular_frequency * capacitance)

    parameters = Pair{String, String}[
        conductor_name => uppercasefirst(String(component.name)),
        outer_name => _pscad_value(conductor.r_ex),
        resistivities[index] => _pscad_value(conductor.material.rho),
        permeabilities[index] => _pscad_value(conductor.material.mu_r),
        insulation_name => _pscad_value(dielectric.r_ex),
        dielectric_permittivities[index] => _pscad_value(dielectric.material.eps_r),
        dielectric_permeabilities[index] => _pscad_value(dielectric.material.mu_r),
        loss_tangents[index] => _pscad_value(loss; maximum = 10)
    ]
    index == 1 && pushfirst!(
        parameters,
        inner_name => _pscad_value(conductor.r_in)
    )
    index > 1 && push!(parameters, "elim$(index - 1)" => "0")
    push!(parameters, "T$(2index + 1)" => "0.0000")
    index == 1 && append!(parameters, [
        "SemiCL" => "0", "SL2" => "0.0000", "SL1" => "0.0000"
    ])
    return parameters
end

function _empty_pscad_part(index::Int)
    radii = (("R1", "R2", "R3"), ("R4", "R4", "R5"),
        ("R6", "R6", "R7"), ("R8", "R8", "R9"))
    resistivities = ("RHOC", "RHOS", "RHOA", "RHOO")
    permeabilities = ("PERMC", "PERMS", "PERMA", "PERMO")
    epsilons = ("EPS1", "EPS2", "EPS3", "EPS4")
    mus = ("PERM1", "PERM2", "PERM3", "PERM4")
    losses = ("LT1", "LT2", "LT3", "LT4")
    _, outer_name, insulation_name = radii[index]
    parameters = Pair{String, String}[
        "CONNAM$index" => "none",
        outer_name => "0.0",
        resistivities[index] => "0.0",
        permeabilities[index] => "0.0",
        insulation_name => "0.0",
        epsilons[index] => "0.0",
        mus[index] => "0.0",
        losses[index] => "0.0000",
        "T$(2index + 1)" => "0.0000"
    ]
    index > 1 && push!(parameters, "elim$(index - 1)" => "0")
    return parameters
end

function _pscad_cable_parameters(
        design,
        position,
        connections,
        index::Int,
        base_frequency
)
    # PSCAD owns this explicit homogenization choice. Its Cable_Coax record
    # requires concentric equivalent layers, so flattening happens here rather
    # than becoming stored CableDesign state.
    components = DataModel.flatten(design, base_frequency)
    length(components) <= 4 || throw(ArgumentError(
        "PSCAD Cable_Coax supports at most four concentric components",
    ))
    length(connections) == length(components) || throw(DimensionMismatch(
        "PSCAD phase mapping must match the cable component count",
    ))
    parameters = Pair{String, String}[
        "CABNUM" => string(index),
        "Name" => design.cable_id,
        "X" => _pscad_value(position.x),
        "OHC" => position.y < 0 ? "0" : "1",
        "Y" => position.y < 0 ? _pscad_value(abs(position.y)) : "0.0",
        "Y2" => position.y > 0 ? _pscad_value(position.y) : "0.0",
        "ShuntA" => "1.0e-11 [mho/m]",
        "FLT" => _pscad_value(base_frequency),
        "RorT" => "0",
        "LL" => string(2length(components) - 1),
        "CROSSBOND" => "0",
        "GROUPNO" => "1",
        "CBC1" => "1",
        "CBC2" => "0",
        "CBC3" => "0",
        "CBC4" => "0",
        "SHRad" => "1",
        "LC" => "3"
    ]
    angular_frequency = 2 * pi * base_frequency
    for (component_index, component) in enumerate(components)
        append!(parameters, _pscad_part_parameters(
            component, component_index, angular_frequency
        ))
        if component_index > 1
            elimination = "elim$(component_index - 1)"
            parameter_index = findlast(pair -> first(pair) == elimination, parameters)
            parameters[parameter_index] = elimination =>
                (connections[component_index] == 0 ? "1" : "0")
        end
    end
    for component_index in (length(components) + 1):4
        append!(parameters, _empty_pscad_part(component_index))
    end
    return parameters
end

function _pscad_project(system::LineCableSystem, earth::EarthModel, base_frequency)
    document = XMLDocument()
    project = ElementNode("project")
    setroot!(document, project)
    _pscad_attributes!(project, (
        name = system.system_id,
        version = "5.0.2",
        schema = "",
        Target = "EMTDC"
    ))
    _pscad_project_settings!(project)
    _pscad_project_scaffolding!(project)

    definitions = addelement!(project, "definitions")
    _pscad_station_definition!(definitions, system.system_id)
    _pscad_main_definition!(definitions, system, base_frequency)

    definition = addelement!(definitions, "Definition")
    _pscad_attributes!(definition,
        (
            id = _PSCAD_IDS.cable_system,
            classid = "RowDefn",
            name = "CableSystem",
            group = "",
            url = "",
            version = "RowDefn",
            build = "RowDefn",
            crc = -1,
            key = "",
            view = "false",
            date = _PSCAD_DEFINITION_DATE
        ))
    _pscad_paramlist!(definition, ["Description" => "", "type" => "Cable"])
    schematic = addelement!(definition, "schematic")
    schematic["classid"] = "RowCanvas"
    _pscad_paramlist!(schematic, [
        "show_grid" => "0",
        "size" => "0",
        "orient" => "1",
        "show_border" => "0"
    ])

    identifier = _PSCAD_IDS.first_physical_component
    _pscad_user!(schematic, identifier, _PSCAD_FREQUENCY_BINDING,
        [
            "FS" => "0.5", "FE" => "1.0E6", "Numf" => "100",
            "DCCOR" => "1", "CPASS" => "0"
        ];
        x = 576, y = 180)
    addelement!(schematic, "grouping")
    identifier += 1
    for (index, (design, position, connections)) in enumerate(zip(
            system.designs,
            system.positions,
            system.connections
    ))
        _pscad_user!(
            schematic,
            identifier,
            _PSCAD_CABLE_BINDING,
            _pscad_cable_parameters(
                design,
                position,
                connections,
                index,
                base_frequency
            );
            x = 234 + (index - 1) * 400,
            y = 612
        )
        identifier += 1
    end
    ground = last(earth.layers)
    _pscad_user!(schematic,
        identifier,
        _PSCAD_GROUND_BINDING,
        [
            "EarthForm2" => "0",
            "EarthForm" => "3",
            "EarthForm3" => "2",
            "GrRho" => "0",
            "GRRES" => _pscad_value(ground.rho),
            "GPERM" => _pscad_value(ground.mu_r),
            "K0" => "0.001",
            "K1" => "0.01",
            "alpha" => "0.7",
            "GRP" => _pscad_value(ground.eps_r)
        ];
        x = 504,
        y = 288)
    _pscad_hierarchy!(project, system.system_id)
    return document
end
