@testitem "Engine / homogeneous dielectric retains constitutive selection across frequency" tags=[:unit] begin
    using Test
    using LineCableModels
    using Measurements: measurement, value, uncertainty
    const E = LineCableModels.Engine
    const DM = LineCableModels.DataModel
    const IE = LineCableModels.ImportExport
    metal = Material(:conductor, 1.72e-8)
    semicon = Material(:semicon, 1e5, 1000.0, 1.0, 20.0, 0.01; tan_delta=0.02)
    dielectric = Material(:insulator, 2e9, 3.1, 1.0, 20.0, 0.02; tan_delta=0.04)
    radii = (0.01, 0.012, 0.02, 0.021)
    source = @cable "radial-mixture" begin
        @terminal :core begin
            solid(metal, Disk(radii[1]))
            screen(semicon; t=radii[2]-radii[1])
            insulation(dielectric; t=radii[3]-radii[2])
            screen(semicon; t=radii[4]-radii[3])
        end
    end
    homogeneous = homogenize(source)
    @test length(homogeneous.geometry.regions) == 2
    material = last(homogeneous.geometry.regions).source.material
    @test material isa RadialDielectric{Float64}
    @test getproperty.(material.materials, :kind) == [:semicon, :insulator, :semicon]
    @test !hasproperty(material, :tan_delta)
    @test !hasproperty(material, :frequency)
    @test @inferred(E.flatten(LineCableModelsCoaxial(), homogeneous, Float64)) isa E.CableBlueprint{Float64}
    @test length(E.flatten(LineCableModelsCoaxial(), homogeneous).dielectrics) == 3
    @test occursin("3 constituents", sprint(show, material))
    @test only(DM.preview_materials(last(homogeneous.geometry.regions))) == material
    @test length(DM.preview_shapes(last(homogeneous.geometry.regions))) == 1
    @test IE.deserialize_value(IE.serialize_value(material)) == material
    reconstructed = IE.deserialize_value(IE.serialize_value(homogeneous))
    @test last(reconstructed.geometry.regions).source.material == material

    frequencies = 10.0 .^ range(-1, 6; length=31)
    for ins in (:default, :Ametani2004), semi in (:default, :Ametani2004)
        formulation = CableConstantsFormulation(insulation_admittance=ins,
            semicon_admittance=semi)
        relations = (formulation.methods.insulation_admittance,
            formulation.methods.semicon_admittance)
        for f in frequencies
            original, reduced = map((source, homogeneous)) do design
                input = E.LocalCableData(E.flatten(LineCableModelsCoaxial(), design))
                y = zeros(ComplexF64, 1, 1)
                E.cable_admittance!(y, input, formulation.methods, f, 20.0,
                    complex(0.0, 2π*f), zeros(ComplexF64, length(input.dielectric_materials)))
                only(y)
            end
            @test imag(reduced) ≈ imag(original) rtol=2e-13
            @test real(reduced) ≈ real(original) rtol=2e-13
            kappa = @inferred constitutive(relations, material, f, 20.0)
            y = 2π * kappa / log(last(radii)/first(radii))
            @test imag(reduced) ≈ imag(y) rtol=2e-13
            @test real(reduced) ≈ real(y) rtol=2e-13
            if ins === semi === :default
                @test real(reduced) == 0
            end
        end
        for f in (50.0, 60.0)
            original = compute(CableConstantsProblem(source; frequency=f), formulation)
            reduced = compute(CableConstantsProblem(homogeneous; frequency=f), formulation)
            @test reduced.C ≈ original.C rtol=2e-13
            @test reduced.G ≈ original.G rtol=2e-13
            exported = only(IE._pscad_components(homogeneous, f, formulation, 20.0)).dielectric
            @test exported.shunt_capacitance ≈ only(original.C) rtol=2e-13
            @test exported.shunt_conductance ≈ only(original.G) rtol=2e-13
        end
    end

    # Independent series circuit, not a baseline regenerated by the implementation.
    ε0 = 8.8541878128e-12
    weights = log.(collect(radii[2:end]) ./ collect(radii[1:end-1]))
    physical = (semicon, dielectric, semicon)
    lossless = (E.InsulationAdmittance.Formula(:default), E.SemiconAdmittance.Formula(:default))
    lossy = (E.InsulationAdmittance.Formula(:Ametani2004), E.SemiconAdmittance.Formula(:Ametani2004))
    for f in (0.1, 50.0, 60.0, 1e3, 1e6)
        expected = inv(sum(q / (2π * (inv(m.rho) + 2π*f*ε0*m.eps_r*(m.tan_delta+im)))
            for (q,m) in zip(weights,physical)))
        actual = 2π * constitutive(lossy, material, f, 20.0) / sum(weights)
        @test actual ≈ expected rtol=2e-13
    end
    changed = RadialDielectric([Material(m.kind, m.rho*1e4, m.eps_r; tan_delta=m.tan_delta*100)
        for m in material.materials], material.weights)
    @test constitutive(lossless, changed, 60.0, 20.0) == constitutive(lossless, material, 60.0, 20.0)
    single = RadialDielectric([dielectric], [0.6])
    subdivided = RadialDielectric([dielectric, dielectric], [0.2, 0.4])
    for f in frequencies
        @test constitutive(lossy, single, f, 20.0) ≈ constitutive(lossy[1], dielectric, f, 20.0)
        @test constitutive(lossy, single, f, 20.0) ≈ constitutive(lossy, subdivided, f, 20.0)
    end
    for correction in (false, true), f in (50.0, 60.0)
        formulation = CableConstantsFormulation(insulation_admittance=:Ametani2004,
            semicon_admittance=:Ametani2004, temperature_dependence=correction ? formula(:default) : nothing)
        original = compute(CableConstantsProblem(source; frequency=f, temperature=60.0), formulation)
        reduced = compute(CableConstantsProblem(homogeneous; frequency=f, temperature=60.0), formulation)
        @test original.C ≈ reduced.C rtol=2e-13
        @test original.G ≈ reduced.G rtol=2e-13
        expected = inv(sum(q / (2π * (inv(m.rho * (correction ? 1+m.alpha*40 : 1)) +
            2π*f*ε0*m.eps_r*(m.tan_delta+im))) for (q,m) in zip(weights,physical)))
        @test only(original.G) ≈ real(expected) rtol=2e-13
        @test only(original.C) ≈ imag(expected)/(2π*f) rtol=2e-13
        @test 2π * constitutive(lossy, material, f, 60.0;
            temperature_dependence=correction ? formulation.methods.temperature_dependence : nothing) / sum(weights) ≈ expected rtol=2e-13
        exported = only(IE._pscad_components(homogeneous, f, formulation, 60.0)).dielectric
        @test exported.shunt_conductance ≈ real(expected) rtol=2e-13
        @test exported.shunt_capacitance ≈ imag(expected)/(2π*f) rtol=2e-13
    end
    @test semicon.T0 == dielectric.T0 == 20.0
    regions = Region(:equivalent, Annulus(0.01, 0.02), Grid((single, subdivided)))
    @test regions isa Gridspace{Region}
    @test length(regions) == 2
    @test isconcretetype(eltype(regions))
    @test @inferred(first(regions)) isa Region
    transported = Gridspace{CableDesign}(homogenize, (Grid((source, source)),))
    @test length(transported) == 2
    @test first(transported) isa CableDesign
    @test last(first(transported).geometry.regions).source.material == material
    uncertain = @cable "uncertain-radial-mixture" begin
        @terminal :core begin
            solid(metal, Disk(0.01))
            insulation(Material(:insulator, 1e10, measurement(3.1, 0.1)); t=0.005)
            insulation(dielectric; t=0.005)
        end
    end
    measured = homogenize(uncertain)
    before = compute(CableConstantsProblem(uncertain), CableConstantsFormulation())
    after = compute(CableConstantsProblem(measured), CableConstantsFormulation())
    @test value.(before.C) ≈ value.(after.C)
    @test uncertainty.(before.C) ≈ uncertainty.(after.C)
    @test only(uncertainty.(after.C)) > 0
    roundtrip = IE.deserialize_value(IE.serialize_value(measured))
    replay = compute(CableConstantsProblem(roundtrip), CableConstantsFormulation())
    @test value.(after.C) ≈ value.(replay.C)
    @test uncertainty.(after.C) ≈ uncertainty.(replay.C)
    @test convert(RadialDielectric{Float32}, single) isa RadialDielectric{Float32}
    @test_throws ArgumentError RadialDielectric([metal], [1.0])
    @test_throws ArgumentError RadialDielectric([dielectric], [-1.0])
    @test_throws DimensionMismatch RadialDielectric([dielectric], [1.0, 2.0])
end

@testitem "ImportExport / homogeneous dielectric library retains constituent laws" tags=[:unit] begin
    using JSON3
    using JSONSchema
    const IE = LineCableModels.ImportExport
    metal = Material(:conductor, 1.72e-8)
    semicon = Material(:semicon, 1e5, 1000.0; tan_delta=0.02)
    dielectric = Material(:insulator, 2e9, 3.1; tan_delta=0.04)
    source = @cable "stored-radial-mixture" begin
        @terminal :core begin
            solid(metal, Disk(0.01))
            screen(semicon; t=0.002)
            insulation(dielectric; t=0.008)
        end
    end
    design = homogenize(source)
    library = CablesLibrary()
    add!(library, design)
    schema_path = joinpath(pkgdir(LineCableModels), "schemas", "cable-design.schema.json")
    schema = JSONSchema.Schema(JSON3.read(read(schema_path, String), Dict{String, Any}))
    mktempdir() do directory
        path = joinpath(directory, "homogeneous.json")
        save(library; file_name=path)
        document = JSON3.read(read(path, String), Dict{String, Any})
        @test JSONSchema.validate(schema, document) === nothing
        restored = CablesLibrary()
        load!(restored; file_name=path)
        actual = restored[design.cable_id]
        @test IE.serialize_value(actual) == IE.serialize_value(design)
        material = last(actual.geometry.regions).source.material
        @test material isa RadialDielectric{Float64}
        @test getproperty.(material.materials, :kind) == [:semicon, :insulator]
        for selector in (:default, :Ametani2004), frequency in (50.0, 60.0)
            formulation = CableConstantsFormulation(insulation_admittance=selector,
                semicon_admittance=selector)
            expected = compute(CableConstantsProblem(design; frequency), formulation)
            replay = compute(CableConstantsProblem(actual; frequency), formulation)
            @test replay.C == expected.C
            @test replay.G == expected.G
        end
    end
end

@testitem "Gmsh FEM / homogeneous dielectric constitutive response retains constituent kinds" tags=[:extension] begin
    using Gmsh
    using LineCableModels
    const FEM = Base.get_extension(LineCableModels, :LineCableModelsGmshExt)
    const E = LineCableModels.Engine
    material = RadialDielectric([Material(:semicon, 1e5, 1000.0, 1.0, 20.0, 0.01; tan_delta=0.02),
        Material(:insulator, 2e9, 3.1, 1.0, 20.0, 0.02; tan_delta=0.04)], [0.2, 0.6])
    design = @cable "homogeneous-fem" begin
        @terminal :core begin
            solid(Material(:conductor, 1.72e-8), Disk(0.01))
            insulation(material; t=0.01)
        end
    end
    system = build(LineCableSystem, design, (0.0, -0.2); connections=Dict(:core=>1))
    problem = LineParametersProblem(system; frequencies=[0.1, 50.0, 60.0, 1e3, 1e6], temperature=60.0,
        earth_props=homogeneous(rho=100.0, eps_r=10.0))
    for ins in (:default, :Ametani2004), semi in (:default, :Ametani2004), correction in (false, true)
        formulation = Formulation(:LineCableModelsFEM; insulation_admittance=ins, semicon_admittance=semi,
            temperature_dependence=correction ? formula(:default) : nothing, options=(ideal_transposition=false,), fem_options=(gmsh_verbosity=0,))
        model = FEM._resolved_fem_model(problem, formulation)
        passive = only(filter(m -> m.kind === :insulator, model.material_plans))
        @test length(model.material_plans) == 2
        relations = (formulation.methods.insulation_admittance, formulation.methods.semicon_admittance)
        @test passive.admittivity ≈ [constitutive(relations, material, f, 60.0;
            temperature_dependence=correction ? formulation.methods.temperature_dependence : nothing) for f in problem.frequencies]
        if ins === semi === :default
            @test all(iszero, real.(passive.admittivity))
        end
    end
end
