using Pkg

# The case catalogue is generated by a separate CLI process in its own project.
# Installing docs dependencies does not instantiate that environment.
Pkg.activate(joinpath(@__DIR__, "..", "test", "gauntlet"))
Pkg.instantiate()

Pkg.activate(@__DIR__)
Pkg.instantiate()
