# This minimal Project.toml ensures Binder installs IJulia.
# Add your own package deps (e.g., LineCableModels, GetDP) later or via a Manifest.

[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"

[compat]
julia = "1.10"

