name: Create Release from Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Extract Changelog Section
        id: changelog
        run: |
          # Grab the section for this tag from CHANGELOG.md
          sed -n "/^## \[${{ github.ref_name }}\]/,/^## \[/p" CHANGELOG.md | \
          sed '$d' > release_notes.md  # Exclude next section header
          cat release_notes.md

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body_path: release_notes.md
          draft: false
          prerelease: false