name: Publish showcase slides
on:
  workflow_dispatch:

concurrency:
  group: showcase
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render showcase 
        run: quarto render docs/showcase/slides

      - name: Deploy to GitHub Pages (subdir)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/showcase/slides/_site
          destination_dir: showcase
          keep_files: true
